language: node_js
node_js:
  - node
  - 12
script:
  - npm run build
  - npm run test
  - npm run lint
  - NODE_ENV=test nyc --silent ava --serial
  - nyc report --reporter=text-lcov | coveralls
  - nyc check-coverage --lines 50
after_success:
  - npm run build
  - semantic-release
notifications:
  email: false
sudo: false
